# Minimal Tempo configuration for local development
# See: https://grafana.com/docs/tempo/latest/configuration/

auth_enabled: false

server:
  http_listen_port: 3200
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1000000
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 48h  # Keep traces for 48 hours

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces

search_enabled: true  # Enable search API
metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
